"""inicial

Revision ID: 20b37fa4055b
Revises: 754f6250de28
Create Date: 2021-08-17 09:25:00.665211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b37fa4055b'
down_revision = '754f6250de28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
