"""pondo repositorio usuario

Revision ID: 358b0a4a0546
Revises: 0b65b7117ba7
Create Date: 2021-08-18 11:08:26.831291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358b0a4a0546'
down_revision = '0b65b7117ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
